#!/usr/bin/env python3
"""Render a single-file, offline, light-theme HTML dashboard.

Design choice that matters: the dashboard is rendered as **static HTML** here in
Python — including inline SVG charts — so it displays correctly even when
JavaScript is blocked (sandboxed preview panels, strict CSP, `file://`, offline).
There is NO CDN dependency and NO required runtime JS. The bundled <script> in
the template is *progressive enhancement only* (collapse/expand, anomaly filters,
drill-down); with it disabled, everything is simply shown expanded.

Inputs (same as before):
  --data       unified.json     (transform.py: meta + rows)
  --anomalies  anomalies.json   (detect_anomalies.py)
  --preflight  preflight.json   (validate_sample.py)
  --insights   insights.json    (WRITTEN BY CLAUDE — schema documented below)

insights.json schema (all optional; provide as much as you can):
{
  "language": "zh"|"en", "title": "...",
  "period": {"from":"...","to":"...","compare_to":"..."},
  "executive_summary": {"health_score":0-100,"takeaways":[...],
                        "top_anomalies":[...],"top_actions":[...]},
  "kpis": [{"label","value","delta_pct","spark":[...],"status":"good|warn|bad","note",
            "benchmark":"optional 'vs benchmark' line, e.g. 'D1 median 12% · Casino/VN/android'"}],
  "anomaly_notes": {"<index>": "plain-language read"},
  "trends": [{"label","dates":[...],"series":{"current":[...],"compare":[...]},
              "as_percent":bool,"note"}],
  "breakdown": {"primary_dim","child_dim","columns":[...],
                "rows":[{"key","values":{},"children":[{"key","values":{}}]}],"note"},
      # a cell value may also be {"v": "-87%", "status": "good|warn|bad"} —
      # rendered colored; use for "vs benchmark" delta columns.
  "breakdowns": [{"title","primary_dim","child_dim","columns","rows","note","group"}],
      # multiple breakdown tables, each its own section — use for the deep
      # report's 分国家 / 分渠道 / 分平台 / ROI / 停留时长 / 分维度留存 tables.
      # "title" names the section; "group" defaults to "analysis".
  "cohorts": {"periods":[...],"retention":[{"label","values":[...],"dashed":bool}],
              "ltv":[{"label","values":[...]}],"note"},
      # "dashed": true renders a gray dashed reference curve — use it for
      # industry benchmark medians (references/benchmarks_2025h2.json).
  "events": {"summary":[{...same shape as kpis...}],
             "funnel":{"stages":[{"label","value","rate_from_prev":0-1}],"note"},
             "top_events":{"columns":[...],"rows":[{"key","values":{}}],"note"},
             "trends":[{...same shape as trends...}],"note"},
      # Events panel. Omit the key entirely when event data wasn't pulled —
      # the builder then renders an honest empty-state card instead.

The dashboard renders as three panels (tabs with JS, stacked sections without):
overview (exec summary, KPIs, recommendations) · analysis (anomalies, trends,
breakdown, cohorts, validation, appendix) · events.
  "recommendations": [{"text","basis","impact","confidence","priority"}],
  "appendix": {"params":{},"degraded_metrics":[...],"notes":"..."}
}

Usage:
  python build_dashboard.py --data unified.json --anomalies anomalies.json \
      --preflight preflight.json --insights insights.json --out dashboard.html
"""
import argparse
import html
import json
import os

PALETTE = ["#3B82F6", "#10B981", "#F59E0B", "#8B5CF6", "#EF4444", "#0EA5E9"]

T = {
 "en": {"exec":"Executive Summary","kpi":"KPI Overview","anom":"Anomaly Center",
        "trends":"Trends","breakdown":"Cross-dimension Breakdown","cohort":"Retention & LTV",
        "valid":"Data Validation","rec":"UA Recommendations","appendix":"Appendix",
        "tab_overview":"Overview","tab_analysis":"Deep Analysis","tab_events":"Event Analysis",
        "ev_summary":"Event Overview","ev_funnel":"Key-event Funnel","ev_top":"Event Volume Ranking",
        "ev_trends":"Event Trends","conv":"conv.",
        "ev_empty":"No event data was pulled in this run. To enable this panel: configure event tracking in Adjust, then pull the events / {event_slug}_events metrics — the funnel, per-install depth, ranking, and event-cliff detection are generated automatically.",
        "health":"Health","takeaways":"Key takeaways","topa":"Top anomalies","topact":"Top actions",
        "all":"All","high":"High","medium":"Medium","low":"Low",
        "change":"Change","base":"Baseline","cause":"Likely cause","action":"Recommendation",
        "query":"Traceable query","none":"No anomalies flagged at current thresholds.",
        "basis":"basis","impact":"impact","conf":"confidence","prio":"priority",
        "sample":"Sample rows","totals":"Core totals","gaps":"Gaps & null warnings",
        "range":"Date range","rows":"Rows","degraded":"Degraded / skipped metrics",
        "params":"Run parameters","whatmeans":"What this means","retention":"Retention","ltv":"LTV",
        "export":"Export / Print","bmk":"Benchmark (Adjust'25Q4)",
        "footer":"Generated by mobile-growth-diagnostics · aggregate, read-only"},
 "zh": {"exec":"高管摘要","kpi":"KPI 概览","anom":"异常检测中心",
        "trends":"趋势分析","breakdown":"跨维度分解","cohort":"留存 & LTV",
        "valid":"数据校验","rec":"投放优化建议","appendix":"附录",
        "tab_overview":"概览","tab_analysis":"数据分析","tab_events":"事件分析",
        "ev_summary":"事件概览","ev_funnel":"关键事件漏斗","ev_top":"事件量排行",
        "ev_trends":"事件趋势","conv":"转化",
        "ev_empty":"本次运行未拉取事件数据。启用方式:在 Adjust 配置事件埋点后,拉取 events / {event_slug}_events 指标——漏斗、人均事件深度、排行与事件断崖检测将自动生成。",
        "health":"健康度","takeaways":"关键结论","topa":"最严重异常","topact":"建议动作",
        "all":"全部","high":"高","medium":"中","low":"低",
        "change":"变化","base":"基线","cause":"原因假设","action":"建议动作",
        "query":"可追溯 query","none":"当前阈值下未发现异常。",
        "basis":"依据","impact":"预期影响","conf":"置信度","prio":"优先级",
        "sample":"样本数据","totals":"核心合计","gaps":"缺口与空值提示",
        "range":"日期范围","rows":"行数","degraded":"降级/跳过的指标",
        "params":"本次参数","whatmeans":"这说明","retention":"留存","ltv":"LTV",
        "export":"导出 / 打印","bmk":"行业基准 (Adjust'25Q4)",
        "footer":"由 mobile-growth-diagnostics 生成 · 聚合·只读数据"},
}


def e(s):
    return html.escape("" if s is None else str(s), quote=True)


STATUS_COLORS = {"bad": "#EF4444", "warn": "#F59E0B", "good": "#10B981"}


def fmt(v):
    if isinstance(v, bool):
        return str(v)
    if isinstance(v, (int, float)):
        return f"{v:,.2f}".rstrip("0").rstrip(".") if isinstance(v, float) else f"{v:,}"
    if isinstance(v, dict) and "v" in v:  # colored cell, e.g. "vs benchmark" delta
        color = STATUS_COLORS.get(v.get("status"))
        style = f' style="color:{color};font-weight:600"' if color else ""
        return f"<span{style}>{e(v['v'])}</span>"
    return e(v)


def signpct(x):
    if x is None:
        return ""
    return f"{'+' if x > 0 else ''}{x*100:.0f}%"


def sparkline(vals, color="#3B82F6", w=120, h=28):
    vals = [v for v in (vals or []) if isinstance(v, (int, float))]
    if len(vals) < 2:
        return ""
    mn, mx = min(vals), max(vals)
    rng = (mx - mn) or 1
    pts = " ".join(f"{(i/(len(vals)-1))*w:.1f},{h-((v-mn)/rng)*(h-4)-2:.1f}"
                   for i, v in enumerate(vals))
    return (f'<svg class="spark" width="{w}" height="{h}" viewBox="0 0 {w} {h}">'
            f'<polyline fill="none" stroke="{color}" stroke-width="2" points="{pts}"/></svg>')


def line_chart(labels, series, as_percent=False, w=520, h=240):
    """series: list of (name, color, [values]) or (name, color, [values], dashed).
    dashed=True renders a gray-dash reference curve (industry benchmarks).
    Returns inline SVG + legend."""
    pad_l, pad_r, pad_t, pad_b = 48, 12, 12, 28
    iw, ih = w - pad_l - pad_r, h - pad_t - pad_b
    allv = [v for s in series for v in s[2] if isinstance(v, (int, float))]
    if not allv:
        return '<div class="muted">—</div>'
    mn, mx = min(allv), max(allv)
    if mn == mx:
        mn, mx = (mn - 1, mx + 1)
    # round axis a touch
    rng = mx - mn
    n = max(len(labels), 1)

    def X(i):
        return pad_l + (i / (n - 1) * iw if n > 1 else iw / 2)

    def Y(v):
        return pad_t + ih - ((v - mn) / rng) * ih

    # gridlines + y labels (4 steps)
    grid, ylab = [], []
    for k in range(5):
        gv = mn + rng * k / 4
        gy = Y(gv)
        grid.append(f'<line x1="{pad_l}" y1="{gy:.1f}" x2="{w-pad_r}" y2="{gy:.1f}" stroke="#E6E8EC" stroke-width="1"/>')
        lab = (f"{gv*100:.1f}%".replace(".0%", "%")) if as_percent else (f"{gv:,.0f}" if abs(gv) >= 10 else f"{gv:,.2f}")
        ylab.append(f'<text x="{pad_l-6}" y="{gy+3:.1f}" text-anchor="end" font-size="10" fill="#5B6472">{e(lab)}</text>')
    # x labels (first / mid / last to avoid clutter)
    xlab = []
    show = sorted(set([0, n//2, n-1])) if n > 1 else [0]
    for i in show:
        if i < len(labels):
            xlab.append(f'<text x="{X(i):.1f}" y="{h-8}" text-anchor="middle" font-size="10" fill="#5B6472">{e(labels[i])}</text>')
    polys, legend = [], []
    for s in series:
        name, color, vals = s[0], s[1], s[2]
        dashed = bool(s[3]) if len(s) > 3 else False
        pts = " ".join(f"{X(i):.1f},{Y(v):.1f}" for i, v in enumerate(vals) if isinstance(v, (int, float)))
        if pts:
            dash = ' stroke-dasharray="6 4"' if dashed else ""
            polys.append(f'<polyline fill="none" stroke="{color}" stroke-width="2"{dash} points="{pts}"/>')
            legend.append(f'<span><i style="background:{color}"></i>{e(name)}</span>')
    svg = (f'<div class="chartwrap"><svg class="chart" width="{w}" height="{h}" viewBox="0 0 {w} {h}" '
           f'preserveAspectRatio="xMidYMid meet">{"".join(grid)}{"".join(ylab)}{"".join(xlab)}{"".join(polys)}</svg></div>')
    leg = f'<div class="legend">{"".join(legend)}</div>' if len(legend) > 1 else ""
    return svg + leg


def health_ring(score):
    if score is None:
        return ""
    deg = max(0, min(100, score)) * 3.6
    style = f"background:conic-gradient(var(--brand) {deg:.0f}deg, var(--line) 0)"
    return f'<div class="ring" style="{style}"><div class="inner">{int(score)}</div></div>'


def render(payload):
    I = payload.get("insights", {}) or {}
    lang = "zh" if str(I.get("language", "en")).lower().startswith("zh") else "en"
    t = T[lang]
    data = payload
    out = []

    # ---- header ----
    title = I.get("title") or ("移动增长诊断" if lang == "zh" else "Mobile Growth Diagnostics")
    p = I.get("period") or {}
    period = ""
    if p:
        period = f'{e(p.get("from",""))} → {e(p.get("to",""))}'
        if p.get("compare_to"):
            period += f'  ·  vs {e(p["compare_to"])}'
    out.append(f'''<header class="top">
      <div><h1>{e(title)}</h1><div class="sub">{period}</div></div>
      <div class="tools"><button class="btn" id="btn-export">{t["export"]}</button></div>
    </header>''')

    # Panel tabs: overview / analysis / events. With JS the nav switches panels;
    # without JS every section renders stacked in this order.
    out.append(f'''<nav class="tabs">
      <a href="#" data-tab="overview" class="active">{t["tab_overview"]}</a>
      <a href="#" data-tab="analysis">{t["tab_analysis"]}</a>
      <a href="#" data-tab="events">{t["tab_events"]}</a></nav>''')

    def sec(title_, body, hint="", group="analysis"):
        h = f' <span class="hint">{e(hint)}</span>' if hint else ""
        out.append(f'<section data-group="{e(group)}"><h2>{e(title_)}{h}</h2>{body}</section>')

    def li(arr):
        if not arr:
            return '<span class="muted">—</span>'
        return '<ul class="clean">' + "".join(f"<li>{e(x)}</li>" for x in arr) + "</ul>"

    # ---- executive summary ----
    ex = I.get("executive_summary")
    if ex:
        body = f'''<div class="card"><div class="grid cols-2" style="align-items:start">
          <div class="health">{health_ring(ex.get("health_score"))}
            <div><div class="muted">{t["health"]}</div>{li(ex.get("takeaways"))}</div></div>
          <div class="grid cols-2">
            <div><div class="muted">{t["topa"]}</div>{li(ex.get("top_anomalies"))}</div>
            <div><div class="muted">{t["topact"]}</div>{li(ex.get("top_actions"))}</div>
          </div></div></div>'''
        sec(t["exec"], body, group="overview")

    # ---- KPIs ----
    def kpi_cards(arr):
        cards = []
        for k in arr:
            d = k.get("delta_pct")
            cls = "flat" if d is None else ("up" if d > 0 else ("down" if d < 0 else "flat"))
            sc = STATUS_COLORS.get(k.get("status"), "#3B82F6")
            bmk = (f'<div class="note" style="color:#5B6472">{t["bmk"]}: {e(k["benchmark"])}</div>'
                   if k.get("benchmark") else "")
            note = f'<div class="note">{t["whatmeans"]}: {e(k["note"])}</div>' if k.get("note") else ""
            cards.append(f'''<div class="card kpi"><div class="label">{e(k.get("label"))}</div>
              <div class="val">{e(k.get("value"))}</div>
              <div class="delta {cls}">{signpct(d)}</div>{sparkline(k.get("spark"), sc)}{bmk}{note}</div>''')
        return cards

    kpis = I.get("kpis") or []
    if kpis:
        sec(t["kpi"], f'<div class="grid kpis">{"".join(kpi_cards(kpis))}</div>', group="overview")

    # ---- recommendations (overview panel: what / so-what / now-what) ----
    rs = I.get("recommendations") or []
    if rs:
        items = []
        for r in rs:
            pr = r.get("priority", "")
            prc = {"high": "b-high", "medium": "b-medium"}.get(pr, "b-low")
            meta = []
            if r.get("basis"):
                meta.append(f'<span>{t["basis"]}: <b>{e(r["basis"])}</b></span>')
            if r.get("impact"):
                meta.append(f'<span>{t["impact"]}: <b>{e(r["impact"])}</b></span>')
            if r.get("confidence"):
                meta.append(f'<span>{t["conf"]}: <b>{e(r["confidence"])}</b></span>')
            if pr:
                meta.append(f'<span>{t["prio"]}: <span class="badge {prc}">{t.get(pr, pr)}</span></span>')
            items.append(f'<div class="rec"><div>{e(r.get("text"))}</div><div class="meta">{"".join(meta)}</div></div>')
        sec(t["rec"], "".join(items), group="overview")

    # ---- anomaly center ----
    an = data.get("anomalies") or []
    notes = I.get("anomaly_notes") or {}
    if an:
        scenarios = []
        for a in an:
            if a.get("scenario") not in scenarios:
                scenarios.append(a.get("scenario"))
        chips = [f'<span class="chip active" data-group="sev" data-val="all">{t["all"]}</span>']
        for v in ("high", "medium", "low"):
            chips.append(f'<span class="chip" data-group="sev" data-val="{v}">{t[v]}</span>')
        chips.append(f'<span class="chip active" data-group="scn" data-val="all">{t["all"]}</span>')
        for s in scenarios:
            chips.append(f'<span class="chip" data-group="scn" data-val="{e(s)}">{e(s)}</span>')
        items = []
        for i, a in enumerate(an):
            sev = a.get("severity", "low")
            note = f'<div class="whatmeans">{t["whatmeans"]}: {e(notes.get(str(i), ""))}</div>' if notes.get(str(i)) else ""
            items.append(f'''<div class="anom" data-sev="{e(sev)}" data-scn="{e(a.get("scenario"))}">
              <div class="head"><span class="badge b-{e(sev)}">{t.get(sev, sev)}</span>
                <span class="metric">{e(a.get("metric"))}</span>
                <span class="slice">{e(a.get("slice"))}</span><span class="chev">▸</span></div>
              <div class="body">{note}<div class="kv">
                <span class="k">{t["change"]}</span><span>{e(a.get("change"))}</span>
                <span class="k">{t["base"]}</span><span>{e(a.get("baseline"))}</span>
                <span class="k">{t["cause"]}</span><span>{e(a.get("cause"))}</span>
                <span class="k">{t["action"]}</span><span>{e(a.get("action"))}</span></div>
                <details class="trace"><summary>{t["query"]}</summary><code>{e(a.get("query"))}</code></details>
              </div></div>''')
        body = f'<div id="anom-center"><div class="filters">{"".join(chips)}</div>{"".join(items)}</div>'
        sec(t["anom"], body, str(len(an)))
    else:
        sec(t["anom"], f'<div class="card muted">{t["none"]}</div>')

    # ---- trends ----
    def trend_cards(trs):
        cards = []
        for tr in trs:
            series = []
            colmap = {"current": "#3B82F6", "compare": "#94A3B8"}
            for j, (name, vals) in enumerate((tr.get("series") or {}).items()):
                series.append((name, colmap.get(name, PALETTE[j % len(PALETTE)]), vals))
            chart = line_chart(tr.get("dates") or [], series, tr.get("as_percent", False))
            note = f'<div class="whatmeans">{t["whatmeans"]}: {e(tr["note"])}</div>' if tr.get("note") else ""
            cards.append(f'<div class="card"><div style="font-weight:600;margin-bottom:6px">{e(tr.get("label"))}</div>{chart}{note}</div>')
        return cards

    trends = I.get("trends") or []
    if trends:
        cards = trend_cards(trends)
        sec(t["trends"], f'<div class="grid {"cols-2" if len(cards) > 1 else ""}">{"".join(cards)}</div>')

    # ---- breakdowns (one section per table: 全局→分国家→分渠道→分平台…) ----
    # `breakdowns` is a list of tables; legacy single `breakdown` still works.
    blist = list(I.get("breakdowns") or [])
    if I.get("breakdown"):
        blist.insert(0, I["breakdown"])
    for bi, b in enumerate(blist):
        if not b or not b.get("rows"):
            continue
        cols = b.get("columns") or []
        head = f'<tr><th>{e(b.get("primary_dim"))}</th>' + "".join(f"<th>{e(c)}</th>" for c in cols) + "</tr>"
        body_rows = []
        for i, r in enumerate(b["rows"]):
            key = f"b{bi}p{i}"
            body_rows.append(f'<tr class="parent" data-key="{key}"><td class="key">{e(r.get("key"))}</td>'
                             + "".join(f"<td>{fmt((r.get('values') or {}).get(c))}</td>" for c in cols) + "</tr>")
            for ch in (r.get("children") or []):
                body_rows.append(f'<tr class="child" data-parent="{key}"><td>{e(ch.get("key"))}</td>'
                                 + "".join(f"<td>{fmt((ch.get('values') or {}).get(c))}</td>" for c in cols) + "</tr>")
        note = f'<div class="whatmeans">{t["whatmeans"]}: {e(b["note"])}</div>' if b.get("note") else ""
        hint = f'{e(b.get("primary_dim",""))}' + (f' × {e(b.get("child_dim"))}' if b.get("child_dim") else "")
        sec(b.get("title") or t["breakdown"],
            f'<div class="card"><table><thead>{head}</thead><tbody>{"".join(body_rows)}</tbody></table>{note}</div>',
            hint, group=b.get("group", "analysis"))

    # ---- cohorts ----
    c = I.get("cohorts")
    if c:
        def cohort_chart(arr, as_pct):
            series = []
            for i, d in enumerate(arr or []):
                dashed = bool(d.get("dashed"))
                color = "#94A3B8" if dashed else PALETTE[i % len(PALETTE)]
                series.append((d.get("label"), color, d.get("values") or [], dashed))
            return line_chart(c.get("periods") or [], series, as_pct)
        cards = (f'<div class="card"><div style="font-weight:600;margin-bottom:6px">{t["retention"]}</div>{cohort_chart(c.get("retention"), True)}</div>'
                 f'<div class="card"><div style="font-weight:600;margin-bottom:6px">{t["ltv"]}</div>{cohort_chart(c.get("ltv"), False)}</div>')
        note = f'<div class="whatmeans">{t["whatmeans"]}: {e(c["note"])}</div>' if c.get("note") else ""
        sec(t["cohort"], f'<div class="grid cols-2">{cards}</div>{note}')

    # ---- data validation ----
    pf = data.get("preflight") or {}
    meta = data.get("meta") or {}
    rows = data.get("rows") or []
    tot = pf.get("core_totals") or {}
    tot_html = "".join(f'<div><span class="muted">{e(k)}</span> <b>{fmt(v)}</b></div>' for k, v in tot.items()) or '<span class="muted">—</span>'
    warns = pf.get("null_warnings") or {}
    warn_html = ("<ul class='clean'>" + "".join(f"<li>{e(k)}: {e(v)}</li>" for k, v in warns.items()) + "</ul>") if warns else '<span class="muted">—</span>'
    gap = f'<div class="badge b-medium">{e(pf["date_gap"])}</div>' if pf.get("date_gap") else ""
    dims = meta.get("dimensions") or []
    mets = (meta.get("metrics") or [])[:6]
    scols = dims + mets
    sample = rows[:6]
    if sample:
        thead = "<tr>" + "".join(f"<th>{e(c)}</th>" for c in scols) + "</tr>"
        srows = "".join("<tr>" + "".join(f"<td>{fmt(r.get(c))}</td>" for c in scols) + "</tr>" for r in sample)
        sample_table = f"<table><thead>{thead}</thead><tbody>{srows}</tbody></table>"
    else:
        sample_table = '<span class="muted">—</span>'
    dr = pf.get("date_range") or {}
    body = f'''<div class="card"><div class="grid cols-3">
      <div><div class="muted">{t["range"]}</div><b>{e(dr.get("from",""))} → {e(dr.get("to",""))}</b>
        <div class="muted">{t["rows"]}: {pf.get("row_count", len(rows))}</div>{gap}</div>
      <div><div class="muted">{t["totals"]}</div>{tot_html}</div>
      <div><div class="muted">{t["gaps"]}</div>{warn_html}</div></div>
      <div style="margin-top:14px"><div class="muted" style="margin-bottom:6px">{t["sample"]}</div>{sample_table}</div></div>'''
    sec(t["valid"], body)

    # ---- appendix ----
    ap = I.get("appendix")
    if ap:
        dl = []
        for k, v in (ap.get("params") or {}).items():
            dl.append(f"<dt>{e(k)}</dt><dd>{e(json.dumps(v, ensure_ascii=False) if isinstance(v, (dict, list)) else v)}</dd>")
        if ap.get("degraded_metrics"):
            dl.append(f'<dt>{t["degraded"]}</dt><dd>{e(", ".join(ap["degraded_metrics"]))}</dd>')
        if ap.get("notes"):
            dl.append(f"<dt>Notes</dt><dd>{e(ap['notes'])}</dd>")
        sec(t["appendix"], f'<div class="card appendix"><dl><dt>{t["params"]}</dt><dd></dd>{"".join(dl)}</dl></div>')

    # ---- events panel ----
    ev = I.get("events")
    if ev:
        if ev.get("summary"):
            sec(t["ev_summary"], f'<div class="grid kpis">{"".join(kpi_cards(ev["summary"]))}</div>',
                group="events")
        fu = ev.get("funnel")
        if fu and fu.get("stages"):
            stages = fu["stages"]
            mx = max((s.get("value") or 0) for s in stages) or 1
            srows = []
            for s in stages:
                w = (s.get("value") or 0) / mx * 100
                rate = s.get("rate_from_prev")
                rate_h = (f'→ {rate*100:.1f}% {t["conv"]}'
                          if isinstance(rate, (int, float)) else "—")
                srows.append(f'<div class="stage"><div class="flabel">{e(s.get("label"))}</div>'
                             f'<div class="fbarwrap"><div class="fbar" style="width:{w:.1f}%"></div>'
                             f'<span class="fval">{fmt(s.get("value"))}</span></div>'
                             f'<div class="frate">{e(rate_h)}</div></div>')
            note = f'<div class="whatmeans">{t["whatmeans"]}: {e(fu["note"])}</div>' if fu.get("note") else ""
            sec(t["ev_funnel"], f'<div class="card"><div class="funnel">{"".join(srows)}</div>{note}</div>',
                group="events")
        te = ev.get("top_events")
        if te and te.get("rows"):
            cols = te.get("columns") or []
            head = "<tr><th></th>" + "".join(f"<th>{e(c)}</th>" for c in cols) + "</tr>"
            trs = "".join(f'<tr><td>{e(r.get("key"))}</td>'
                          + "".join(f"<td>{fmt((r.get('values') or {}).get(c))}</td>" for c in cols)
                          + "</tr>" for r in te["rows"])
            note = f'<div class="whatmeans">{t["whatmeans"]}: {e(te["note"])}</div>' if te.get("note") else ""
            sec(t["ev_top"], f'<div class="card"><table><thead>{head}</thead><tbody>{trs}</tbody></table>{note}</div>',
                group="events", hint=str(len(te["rows"])))
        if ev.get("trends"):
            cards = trend_cards(ev["trends"])
            sec(t["ev_trends"], f'<div class="grid {"cols-2" if len(cards) > 1 else ""}">{"".join(cards)}</div>',
                group="events")
    else:
        # honest empty state: say what's missing and how to enable it
        sec(t["tab_events"], f'<div class="card muted">{t["ev_empty"]}</div>', group="events")

    gen = (meta.get("generated_at") or "")
    foot = t["footer"] + (f" · @ {e(gen)}" if gen else "") + (" · ROAS/ROI 显示为% (API 返回小数)" if lang == "zh" else " · ROAS/ROI shown as % (API returns decimals)")
    out.append(f'<footer>{foot}</footer>')
    return "\n".join(out)


def _load(path):
    if not path:
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", required=True)
    ap.add_argument("--insights", required=True)
    ap.add_argument("--anomalies")
    ap.add_argument("--preflight")
    ap.add_argument("--template")
    ap.add_argument("--out", required=True)
    args = ap.parse_args(argv)

    here = os.path.dirname(__file__)
    template = args.template or os.path.join(here, "..", "assets", "dashboard_template.html")
    with open(template, "r", encoding="utf-8") as f:
        shell = f.read()

    data = _load(args.data) or {}
    anomalies = _load(args.anomalies) or {}
    payload = {
        "meta": data.get("meta", {}),
        "rows": data.get("rows", []),
        "anomalies": anomalies.get("anomalies", anomalies if isinstance(anomalies, list) else []),
        "preflight": _load(args.preflight) or {},
        "insights": _load(args.insights) or {},
    }

    marker = "<!--__CONTENT__-->"
    if marker not in shell:
        raise SystemExit(f"Template is missing the marker {marker}")
    html_out = shell.replace(marker, render(payload))
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(html_out)
    print(f"Dashboard written -> {args.out} ({len(payload['rows'])} rows, {len(payload['anomalies'])} anomalies)")


if __name__ == "__main__":
    main()
